TTS snippets for Synthesize and ListVoices methods
TinkoffCreditSystems/tinkoff-speech-api-examples pull request #45
Opened 2021-06-24 21:54 UTC by nikolai-semenov

2021-06-25 07:56 UTC, dukanov commented on python/snippets/tts_synthesize_rest_linear16_playback.py
> +assert build_request() == build_request_from_pb()
Мб сделать автотесты, а в сниппетах хранить минимальный рабочий код?

2021-06-25 07:58 UTC, nikolai-semenov commented on python/snippets/tts_synthesize_rest_linear16_playback.py
> +assert build_request() == build_request_from_pb()
Я просто в документации хочу указать, что запросы в REST API можно генерить как руками, так и из прото. Но `assert` можно убрать, да.

2021-09-06 10:25 UTC, dukanov requested changes

2021-09-06 10:25 UTC, dukanov commented on python/snippets/tts_synthesize_ogg_opus.py
> +            audio_encoding=tts_pb2.RAW_OPUS,
мб вынесем как аргумент и сделаем argparse-выбор
так же аргумент для текста
как результат, сократим количество скриптов вдвое

2021-09-06 10:25 UTC, dukanov commented on python/snippets/gen_jwt.sh
> +#!/usr/bin/env bash
плиз, добавь в readme примеры работы с этими скриптами, а то скрипты есть, а инфы о их присутствии нет :)

2021-09-06 12:50 UTC, dukanov commented on python/snippets/tts_synthesize_ogg_opus.py
> +        ),
не хватает voice_name для ясности

2021-09-07 10:51 UTC, nikolai-semenov commented on python/snippets/tts_synthesize_ogg_opus.py
> +            audio_encoding=tts_pb2.RAW_OPUS,
В принципе, можно так сделать, но у нас [текущая структура примеров](https://voicekit.tinkoff.ru/docs/ttstutorial/) построена так, что на каждый пример есть свой сниппет здесь.

2021-09-07 10:52 UTC, nikolai-semenov commented on python/snippets/gen_jwt.sh
> +#!/usr/bin/env bash
Инфа есть в туториалах на https://voicekit.tinkoff.ru/docs/, я тогда добавлю короткое README в эту директорию

2021-09-08 08:50 UTC, dukanov approved these changes

2021-09-08 08:52 UTC, merged